import type { BlogPost } from '@/lib/types';

const SOURCES = [
  { label: 'Bicycle Network: Rules for rideables', url: 'https://bicyclenetwork.com.au/newsroom/2026/09/23/rules-for-rideables' },
  { label: 'Product Safety Australia: E-bikes, e-scooters and e-micromobility devices', url: 'https://www.productsafety.gov.au/business/e-bikes-e-scooters-and-other-e-micromobility-devices' },
];

const NOTE = 'Rules and prices change, so check your state road authority and the retailer before you buy.';

/** Full-length structured guides (rich layout). Slugs match the original short posts so URLs are unchanged. */
export const GUIDE_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    slug: 'how-much-are-electric-bicycles',
    title: 'How Much Are Electric Bicycles in Australia? (2026 Price Guide)',
    seoTitle: 'Electric Bicycle Price Australia | How Much Are E-Bikes?',
    excerpt:
      'How much are electric bicycles in Australia? Entry-level, mid-tier and premium electric bicycle price ranges, running costs, and what drives the cost of an e-bike.',
    category: 'Buying Guides',
    readTime: '7 min read',
    date: 'October 2026',
    isoDate: '2026-10-10',
    author: 'e bikes for sale team',
    image: '/images/catalog/electric-commuter-bikes.webp',
    altText: 'Electric bicycle price comparison: commuter e-bike on an Australian street',
    productSlug: 'pedal-comet-3-disc-electric-hybrid-bike-charcoal',
    tags: ['electric bicycle price', 'electric bicycle cost', 'ebikes cost', 'price e bike', 'cheap electric bikes'],
    content: [
      'How much are electric bicycles in Australia? Most new e-bikes sit between about $1,200 and $8,000, and the right figure for you depends on how far you ride, how hilly your route is and how much weight you carry. This guide explains the electric bicycle price tiers, what you get at each level, and the running costs most buyers forget to budget for.',
      '## How much are electric bicycles? The three price tiers',
      'Electric bicycle price in Australia falls into three broad bands. Use them as a guide, not a quote, because retailers, model years and promotions all move the number.',
      '1. Entry-level commuters ($1,200 to $1,800): a 250W rear hub motor, a 360 to 500 Wh battery and mechanical disc brakes. Suits flat commutes of up to about 15 km each way.\n2. Mid-tier commuter, cargo and trail bikes ($1,900 to $3,500): stronger torque, hydraulic disc brakes, puncture-resistant tyres and 600 to 840 Wh batteries for roughly 70 to 110 km of range. This is where most buyers find the best value.\n3. Premium mid-drive and carbon eMTBs ($3,800 to $8,000 and up): torque-sensing mid-drive motors, air suspension and lightweight frames built for demanding trails and heavy daily use.',
      '## What drives the cost of an electric bicycle?',
      'Two bikes that look similar can differ by thousands of dollars. These are the factors that move the electric bicycle cost:',
      '- Motor type: a hub motor is simpler and cheaper, while a mid-drive motor delivers more natural power and climbs better.\n- Battery size: measured in watt-hours (Wh). More Wh means more range and a higher price.\n- Brakes and components: hydraulic discs, quality drivetrains and reliable tyres cost more and last longer.\n- Frame and weight: aluminium is the norm, carbon lifts both performance and price.\n- Compliance and warranty: a bike that meets EN 15194 and carries an Australian warranty costs more than a grey import, and it is worth it.',
      '## Is a cheap electric bike worth it?',
      'A lower price can be sensible if your use is light: short, flat trips and a rider under about 90 kg. Our cheap electric bikes guide covers where to save and where not to. Be cautious with very low prices. A bike that is far below the market usually cuts corners on the battery cells, brakes or frame, and a poor battery is the most expensive part to replace.',
      '## Running costs: what an e-bike costs after you buy it',
      'Buying price is only part of the picture. Budget for these ongoing costs:',
      '- Charging: a 500 Wh battery holds about half a kilowatt-hour, which typically costs around 15 cents to fill at household electricity rates.\n- Servicing: a yearly service, chain and brake pad wear and tyre replacement usually add up to a few hundred dollars a year for a daily rider.\n- Battery replacement: a quality lithium battery commonly lasts several years of daily use, and a replacement is a significant cost, often several hundred dollars or more.\n- Accessories: a certified helmet, a strong lock and lights. Budget for these on day one.',
      '## E-bike versus car or public transport',
      'For short urban trips, the maths tends to favour the e-bike. There is no fuel, no registration or parking cost, and servicing is far cheaper than a car. Many riders find an e-bike pays for itself within a year or two if it replaces regular car trips or a daily transit fare. Your own saving depends on your commute, so add up what you spend now before you compare.',
      '## How to choose without overspending',
      'Start with your ride, not the price tag. Work out your daily distance, the hills on your route and what you need to carry, then match a battery and motor to that. A rider with a flat 8 km commute does not need a 840 Wh mountain bike, and a rider with steep hills should not buy the cheapest hub-motor commuter. If you are unsure, browse our electric commuter bikes or the full e-bike range and compare battery size, brakes and warranty side by side.',
      NOTE,
    ].join('\n\n'),
    faqs: [
      { q: 'How much are electric bicycles in Australia?', a: 'Most new e-bikes cost between about $1,200 and $8,000. Entry-level commuters start around $1,200, mid-tier bikes run roughly $1,900 to $3,500, and premium mid-drive or carbon eMTBs start near $3,800.' },
      { q: 'What is a good price for a first electric bicycle?', a: 'For most commuters, $1,500 to $2,500 buys a reliable bike with a decent battery and hydraulic or good mechanical brakes. Spend more if you have hills or heavy loads.' },
      { q: 'How much does it cost to charge an e-bike?', a: 'A full charge of a typical 500 Wh battery uses about half a kilowatt-hour, which is usually around 15 cents at household rates.' },
      { q: 'How long does an e-bike battery last?', a: 'A quality lithium battery usually lasts several years of regular use, and capacity fades gradually. Replacement is the biggest ongoing cost.' },
      { q: 'Are cheap grey-import e-bikes worth it?', a: 'Be careful. They may lack an Australian warranty, the correct charger or proper compliance, and very low prices can signal poor-quality battery cells.' },
    ],
    sources: SOURCES,
    related: [
      { label: 'Electric commuter bikes', href: '/ebikes/electric-commuter-bikes' },
      { label: 'Cheap electric bikes', href: '/cheap-electric-bikes' },
      { label: 'All e-bikes', href: '/ebikes' },
      { label: 'E-bike size guide', href: '/blog/bike-size-guide-electric-bicycles' },
    ],
  },
  {
    id: 'blog-2',
    slug: 'how-fast-does-an-electric-bicycle-go',
    title: 'How Fast Does an Electric Bicycle Go in Australia? (Speed Limits & Laws Explained)',
    seoTitle: 'How Fast Does an Electric Bicycle Go? Australian Speed Limits',
    excerpt:
      'How fast does an electric bicycle go in Australia? The 25 km/h assist limit, 250W rule, what happens when you ride faster, and how shared-path speed limits apply.',
    category: 'Safety & Compliance',
    readTime: '6 min read',
    date: 'October 2026',
    isoDate: '2026-10-10',
    author: 'e bikes for sale team',
    image: '/images/catalog/fat-tyre-electric-bicycle.webp',
    altText: 'Electric bicycle speed: rider on a commuter e-bike on an Australian bike path',
    productSlug: 'pedal-comet-3-disc-electric-hybrid-bike-charcoal',
    tags: ['electric bicycle speed', 'e bike speed limit australia', 'en 15194', '250w ebike', 'e bike laws'],
    content: [
      'How fast does an electric bicycle go? A road-legal e-bike in Australia gives you motor assistance up to 25 km/h. Above that speed the motor cuts out, and you ride on your own legs like any other bicycle. This guide explains the rules behind that number, what you will actually feel on the road, and how local speed limits apply.',
      '## The Australian rule: 25 km/h and 250W',
      'Under the standard used in Australia, EN 15194, a pedal-assist electric bicycle has a motor with a continuous rated power of no more than 250 watts, and the motor must stop assisting once you reach 25 km/h. That is why compliant e-bikes are treated as bicycles rather than motor vehicles: no licence, no registration and no insurance requirement for standard models.',
      '- Motor limit: 250W continuous rated power.\n- Assist limit: assistance stops at 25 km/h.\n- Pedal assist: the motor only helps while you pedal. A small walk-assist function up to about 6 km/h is allowed.',
      '## How fast can you really go?',
      'The 25 km/h limit is the assist cut-off, not a hard speed cap. You can go faster by pedalling harder, riding downhill or with a tailwind, and the bike will not slow you down. The motor simply stops helping, and a heavy e-bike will feel a little more sluggish above that speed because of its extra weight.',
      'Most commuters find 20 to 25 km/h feels fast and natural. It is also roughly twice the speed of an average casual rider, which is the whole point: hills, headwinds and longer distances become easy.',
      '## Why you should not fit a speed hack',
      'Online "unlock" kits and chips that remove the 25 km/h limit exist, and using them is a mistake. A modified e-bike that assists beyond the limit or exceeds the power rule is no longer a bicycle in the eyes of the law. It can need registration and a licence, it can void your warranty and insurance, and it puts you and others at risk on shared paths. Brakes, frame and tyres on a standard e-bike are designed for the standard speed.',
      '## Speed limits on shared paths and roads',
      'Being legal at 25 km/h does not mean you can ride 25 km/h everywhere. Shared paths and some urban areas have lower limits, and the numbers differ by state and council. Slow down around pedestrians, near driveways and on crowded paths, and always follow the signage. On roads, ride with traffic and obey the same rules as other bicycles.',
      '## E-scooters are different',
      'Electric scooters follow separate rules in each state, with their own speed and power limits and rules about where they can be used. Do not assume the e-bike rules apply to a scooter. Check your state road authority before you ride one on public paths.',
      '## What affects real-world speed and range?',
      '- Assist level: higher assist drains the battery faster.\n- Weight: rider, cargo and the bike itself.\n- Terrain and wind: hills and headwinds use more power.\n- Tyre pressure and condition: soft tyres cost you speed and range.\n- Battery size and health: a larger, healthy battery holds assist longer.',
      NOTE,
    ].join('\n\n'),
    faqs: [
      { q: 'How fast does an electric bicycle go?', a: 'A compliant e-bike in Australia assists up to 25 km/h. You can pedal faster than that, but the motor stops helping above 25 km/h.' },
      { q: 'What is the legal power limit for an e-bike in Australia?', a: 'A compliant pedal-assist e-bike has a motor of up to 250W continuous rated power under EN 15194, with assist cutting out at 25 km/h.' },
      { q: 'Do I need a licence or registration for an e-bike?', a: 'Not for a standard EN 15194 compliant pedal-assist e-bike. Modified or higher-powered bikes may be treated as motor vehicles. Check your state rules.' },
      { q: 'Can I remove the 25 km/h speed limit?', a: 'You should not. A bike modified past the limit may no longer count as a bicycle, can need registration, and may void warranty and insurance.' },
      { q: 'Are electric scooters limited to the same speed?', a: 'No. Scooters follow separate state rules for speed, power and where they can be ridden. Check your state road authority.' },
    ],
    sources: SOURCES,
    related: [
      { label: 'Electric commuter bikes', href: '/ebikes/electric-commuter-bikes' },
      { label: 'All e-bikes', href: '/ebikes' },
      { label: 'How much are electric bicycles?', href: '/blog/how-much-are-electric-bicycles' },
      { label: 'Helmet guide for youth riders', href: '/blog/helmet-youth-bike-australian-standards' },
    ],
  },
  {
    id: 'blog-3',
    slug: 'bike-size-guide-electric-bicycles',
    title: 'E-Bike Size Guide Australia: Electric Bicycle Height & Frame Chart',
    seoTitle: 'E-Bike Size Guide Australia | Electric Bicycle Frame Chart',
    excerpt:
      'Find your e-bike size: a height and frame chart for electric bicycles, how to read standover and reach, and tips for step-through, folding and mountain e-bikes.',
    category: 'Buying Guides',
    readTime: '6 min read',
    date: 'October 2026',
    isoDate: '2026-10-10',
    author: 'e bikes for sale team',
    image: '/images/catalog/electric-mountain-bike.webp',
    altText: 'E-bike size guide: rider checking frame size on an electric bicycle',
    productSlug: 'pedal-derby-electric-folding-bike',
    tags: ['e bike size guide', 'electric bicycle frame size', 'bike size chart', 'step through ebike', 'ebike fit'],
    content: [
      'Choosing the right e-bike size matters more on an electric bicycle than on a normal bike: the extra weight makes a bad fit harder to ignore, and the wrong frame size affects comfort, control and safety. This e-bike size guide gives you a height-based frame chart, shows how to check fit in person, and explains how step-through, folding and mountain e-bikes differ.',
      '## E-bike size chart by rider height',
      'Use this chart as a starting point. Sizing varies between brands, so always check the manufacturer chart for the exact model.',
      '- 150 to 165 cm: small frame (about 15 to 16 inch, or 38 to 41 cm)\n- 165 to 175 cm: medium frame (about 17 to 18 inch, or 43 to 46 cm)\n- 175 to 185 cm: large frame (about 19 to 20 inch, or 48 to 51 cm)\n- 185 cm and over: extra-large frame (about 21 to 22 inch, or 53 to 56 cm)',
      'If you sit between two sizes, riders who want a more upright, relaxed position usually choose the smaller frame. Riders who want a stretched, sportier position, or who are tall in the leg, usually choose the larger one.',
      '## How to check the fit',
      'A chart gets you close. These four checks confirm it:',
      '1. Standover height: with both feet flat on the ground, you should have a few centimetres of clearance over the top tube. Step-through frames remove this concern.\n2. Saddle height: when sitting, your leg should be almost fully extended at the bottom of the pedal stroke, with a slight bend in the knee.\n3. Reach: you should hold the handlebars without stretching, with your elbows slightly bent and your back comfortable.\n4. Control: you should be able to stop and put a foot down confidently, because e-bikes are heavier than they look.',
      '## Step-through, diamond and folding frames',
      'The frame type changes how you size. A step-through frame is easier to mount, which suits shorter riders and anyone who dislikes swinging a leg over the bike. A diamond frame is stiffer and generally lighter for the same strength. A folding e-bike uses adjustable seatposts and handlebar stems, so one size often fits a wide range of heights, which makes it popular for mixed-height households.',
      '## Mountain, cargo and kids e-bikes',
      'Mountain e-bikes are sized by frame size and often by wheel size too, so check both. Cargo e-bikes tend to have long wheelbases and low step-throughs for loading, and the fit matters most when you carry a load. For children, wheel size works better than height alone: a 24 inch wheel suits many older kids, as covered on our kids mountain bike page.',
      '## Common sizing mistakes',
      '- Choosing by wheel size alone. Frame size and reach matter more.\n- Buying too large to "grow into" the bike. An oversized e-bike is harder to control.\n- Ignoring saddle and stem adjustment. Small tweaks often fix a bike that feels slightly off.\n- Skipping a test ride. If you can, try the bike or confirm the return policy.',
      NOTE,
    ].join('\n\n'),
    faqs: [
      { q: 'What size e-bike do I need for my height?', a: 'As a guide, 150 to 165 cm suits a small frame, 165 to 175 cm a medium, 175 to 185 cm a large and 185 cm and over an extra-large. Always check the manufacturer chart.' },
      { q: 'Is e-bike sizing different from a normal bike?', a: 'The chart is similar, but the extra weight makes fit and standover more important. A step-through frame is a common way to make an e-bike easier to mount.' },
      { q: 'What size is a 26 or 29 inch e-bike wheel?', a: 'Wheel size is separate from frame size. Wheel diameter is chosen for the bike type, and frame size is chosen for your height and reach.' },
      { q: 'What if I am between sizes?', a: 'Choose the smaller frame for a relaxed upright position or the larger frame for a stretched sporty position, and adjust saddle and stem to fine-tune.' },
      { q: 'Do folding e-bikes come in sizes?', a: 'Most folding e-bikes have adjustable seatposts and stems, so one frame usually fits a wide range of rider heights.' },
    ],
    sources: SOURCES,
    related: [
      { label: 'Folding e-bikes', href: '/ebikes/folding-e-bike' },
      { label: 'Kids mountain bikes (24 inch)', href: '/ebikes/electric-mountain-bike/kids-mountain-bikes' },
      { label: 'Electric commuter bikes', href: '/ebikes/electric-commuter-bikes' },
      { label: 'How much are electric bicycles?', href: '/blog/how-much-are-electric-bicycles' },
    ],
  },
  {
    id: 'blog-4',
    slug: 'helmet-youth-bike-australian-standards',
    title: 'Helmet Youth Bike Guide: Kids & E-Bike Helmets and AS/NZS 2063 Explained',
    seoTitle: 'Helmet Youth Bike Guide | AS/NZS 2063 Australian Standards',
    excerpt:
      'Helmet youth bike guide for Australia: AS/NZS 2063 certification, sizing and fit, features worth paying for, and when to replace a kids or e-bike helmet.',
    category: 'Safety & Compliance',
    readTime: '6 min read',
    date: 'October 2026',
    isoDate: '2026-10-10',
    author: 'e bikes for sale team',
    image: '/images/catalog/e-bike-helmets.webp',
    altText: 'Helmet youth bike: certified Australian safety helmet on a young cyclist',
    productSlug: 'met-crackerjack-kids-helmet-mint-matt',
    tags: ['helmet youth bike', 'e bike helmet', 'kids bike helmet', 'as nzs 2063', 'childrens cycling helmets'],
    content: [
      'A helmet is the most important piece of kit you will buy for a youth bike or e-bike, and in Australia it is also the law. This guide explains what to look for in a helmet youth bike riders can trust: the AS/NZS 2063 certification, how to size and fit it, which features are worth paying for and when to replace it.',
      '## Are helmets compulsory in Australia?',
      'Yes. Wearing an approved bicycle helmet is required for all bicycle riders in every state and territory, and that includes children, passengers and e-bike riders. Rules cover riders on roads and paths, so a helmet is a must for any youth bike, scooter or e-bike ride in a public place. Check your state road authority for the exact rules and penalties.',
      '## What does AS/NZS 2063 mean?',
      'AS/NZS 2063 is the Australian and New Zealand standard for bicycle helmets. A helmet that meets it has been tested for impact absorption, strap strength and retention. Look for the standard marked on the helmet and its packaging before you buy, and treat any helmet without it as unsuitable. Check for the AS/NZS 2063 label yourself before you buy.',
      '## How to size and fit a youth helmet',
      'A good fit matters more than any feature. Measure the head circumference just above the eyebrows, then match it to the sizing on the box. Then check:',
      '1. Level: the helmet sits flat and low on the forehead, about two fingers above the eyebrows.\n2. Side straps: they form a "V" just below each ear.\n3. Chin strap: snug enough that you can fit only one or two fingers between the strap and chin.\n4. Wobble test: with the strap done up, the helmet should not rock forward, back or sideways when the child shakes their head.',
      '## Features worth paying for',
      '- Dial-fit retention: lets you fine-tune the fit as a child grows and keeps the helmet stable.\n- Easy buckle: a buckle a child can fasten without pinching encourages them to wear it every ride.\n- Rear light or reflective detail: improves visibility at dawn, dusk and on shared paths.\n- Ventilation and light weight: a comfortable helmet is a helmet that actually gets worn.\n- Visor: helps against sun glare and light rain.',
      '## Do e-bike riders need a special helmet?',
      'For a standard EN 15194 e-bike limited to 25 km/h, a helmet certified to AS/NZS 2063 is the right choice. Searches for an "e bike helmet" or "electric bike helmet" often point to extended coverage at the back of the head, extra ventilation or built-in lights. Those are useful extras, but certification comes first.',
      '## When to replace a helmet',
      'Replace a helmet after any significant impact, even if it looks undamaged, because the foam is designed to compress once. Also replace it when it is damaged, when the straps fray or when your child outgrows it. Many manufacturers recommend replacing a helmet every few years. Never buy a second-hand helmet when you do not know its history.',
      '## Quick checklist before every ride',
      '- Helmet fits and the strap is done up.\n- Lights and reflectors work.\n- Tyres are firm and brakes respond.\n- The child knows where they can and cannot ride.',
      NOTE,
    ].join('\n\n'),
    faqs: [
      { q: 'Do kids have to wear a helmet on a bike in Australia?', a: 'Yes. Approved helmets are required for all bicycle riders in every state and territory, including children and e-bike riders.' },
      { q: 'What is AS/NZS 2063?', a: 'It is the Australian and New Zealand standard for bicycle helmets, covering impact absorption, strap strength and retention.' },
      { q: 'How should a youth helmet fit?', a: 'It should sit level and low, two fingers above the eyebrows, with side straps forming a V below the ears and a snug chin strap.' },
      { q: 'Do I need a different helmet for an electric bike?', a: 'For a standard EN 15194 e-bike limited to 25 km/h, an AS/NZS 2063 certified helmet is the right choice. Extra coverage and lights are useful extras.' },
      { q: 'How often should I replace a bike helmet?', a: 'Replace it after any significant impact, when it is damaged, or when it no longer fits. Many manufacturers also recommend replacement every few years.' },
    ],
    sources: SOURCES,
    related: [
      { label: 'Kids bike helmets', href: '/kids-bike-helmets' },
      { label: 'Kids electric bikes', href: '/ebikes/kids-electric-bikes' },
      { label: 'Kids mountain bikes', href: '/ebikes/electric-mountain-bike/kids-mountain-bikes' },
      { label: 'How fast does an electric bicycle go?', href: '/blog/how-fast-does-an-electric-bicycle-go' },
    ],
  },
];
