// GENERATED from the Semrush AU keyword bank (see seo-strategy/ebikes-page-keyword-map.md). Do not hand-edit.
// Each node has ONE primary (KD <= 24) and up to 6 secondary keywords. Non-electric search terms are included on purpose.
export interface NodeKeywords { primary: string; primaryVolume: number; primaryKd: number; secondary: string[]; supporting: string[] }
export const CATALOG_KEYWORDS: Record<string, NodeKeywords> = {
  'hub': { primary: "best electric bike australia", primaryVolume: 1300, primaryKd: 12, secondary: ["ebike","electric bike","electric bicycle","electric bicycle ebike","e bike australia","electric bike australia"], supporting: ["good electric bicycle","best e cycle","bicycle electric bike","3 wheel electric bike","best e bikes australia","best electric bikes"] },
  'emtb': { primary: "electric mountain bike", primaryVolume: 3600, primaryKd: 19, secondary: ["mountain bikes","mountain e cycle","mtb bikes","ebikes mountain","emtb australia","ebike mtb"], supporting: ["mountain electric cycle","mountain bikes for sale","mountain bicycle for sale","mtb bicycle for sale","e mountain bike","e mtb"] },
  'emtb-hardtail': { primary: "electric hardtail mountain bike", primaryVolume: 70, primaryKd: 6, secondary: ["hardtail mountain bikes","hardtail mtb for sale","hardtail mountain bikes for sale","hardtail e mountain bike","cheap hardtail mountain bikes"], supporting: [] },
  'emtb-dual': { primary: "dual suspension electric mountain bike", primaryVolume: 170, primaryKd: 7, secondary: ["dual suspension ebike","dual suspension mtb for sale","full suspension e mtb","full suspension electric bicycle","dual suspension electric bike","electric full sus mountain bike"], supporting: ["full sus emtb","dual suspension emtb"] },
  'emtb-enduro': { primary: "downhill mountain bike", primaryVolume: 1900, primaryKd: 16, secondary: ["mtb downhill mountain bike","affordable downhill mtb","mtb downhill bikes","downhill bike","downhill mtb","downhill cycle"], supporting: ["dh bike mtb","dh mountain bike","bike for downhill","downhill mountain biking bikes","cheap dh bikes","cheap downhill mountain bike"] },
  'emtb-trail': { primary: "electric trail bicycle", primaryVolume: 260, primaryKd: 16, secondary: ["off road electric bike australia","off roading electric bike","electric trail bike australia","all mountain mtb bikes"], supporting: [] },
  'folding': { primary: "folding e bike", primaryVolume: 1300, primaryKd: 10, secondary: ["best folding bikes","collapsible bicycles","foldable e bicycle","e bike collapsible","best fold up electric bike","fold bike"], supporting: ["fold up electric bicycle","folding bike","fold away bike","cycling folding bike","bike collapsible","foldable electric bike"] },
  'cruiser': { primary: "electric cruiser bikes", primaryVolume: 110, primaryKd: 9, secondary: ["cruiser bikes","cruiser e bike","electric cruiser bike australia","cruiser e bikes australia","e cruiser bike"], supporting: [] },
  'fat-tyre': { primary: "fat tyre electric bicycle", primaryVolume: 1600, primaryKd: 18, secondary: ["fat bike","fat tyre ebike","fat tyre electric bike","electric fat bike","electric bicycle fat bike","fat electric bicycle"], supporting: ["fat e bike","fat wheel electric bike","fatbike","fat tyre bike","e fat bike","fat wheel electric bicycle"] },
  'cargo': { primary: "electric cargo bike", primaryVolume: 720, primaryKd: 16, secondary: ["cargo bike","electric cargo bicycle","cargo e bike","cargo e cycle","cargo bicycle","cargo cycles"], supporting: ["cargo bike australia","cargo bicycle australia","e cargo bike","cargo cycling","electric cargo bike australia","cargo ebike australia"] },
  'road': { primary: "electric road bike", primaryVolume: 720, primaryKd: 15, secondary: ["electric gravel bike","road bicycle electric","e gravel bike","gravel ebike","electric road bike australia","e road bikes australia"], supporting: [] },
  'commuter': { primary: "electric commuter bikes", primaryVolume: 480, primaryKd: 15, secondary: ["electric hybrid","light hybrid bicycle","hybrid bike","hybrid cycle bike","hybrid cycling bikes","commuter bike"], supporting: ["electric bike for commuters","commuter e-bike","trekking e bike","e bike women","hybrid ebike","electric hybrid bikes"] },
  'sc-electric': { primary: "push scooter electric", primaryVolume: 170, primaryKd: 21, secondary: ["electric scooters top rated","recreational e scooters","e scooter price in australia","foldable scooters","electric foot scooter","folding electric scooters"], supporting: ["cheap good e scooters","best e-scooters"] },
  'sc-adults': { primary: "e scooter adults", primaryVolume: 320, primaryKd: 16, secondary: ["push scooter adults","motorized scooter for adults","adult escooter","collapsible electric scooter for adults","electric scooter foldable adults","escooter for adults"], supporting: ["foldable electric scooter for adults","adult scooter kick","folding electric scooter for adults","adults electric scooter","e scooters for adults"] },
};
