// GENERATED by seo-strategy/preview-site/apply-pics.js from the supplier photo folder. Do not hand-edit.
export const PRODUCT_IMAGES: Record<string, string[]> = {
  "cube-reaction-hybrid-performance-600-fe-easy-entry-electric-hardtail-mountain-bike": [
    "/images/products/cube-reaction-hybrid-performance-600-fe-easy-entry-electric-hardtail-mountain-bike.webp"
  ],
  "pedal-uptown-sl-electric-vintage-cruiser-bike-7-speed": [
    "/images/products/pedal-uptown-sl-electric-vintage-cruiser-bike-7-speed.webp",
    "/images/products/pedal-uptown-sl-electric-vintage-cruiser-bike-7-speed-2.webp",
    "/images/products/pedal-uptown-sl-electric-vintage-cruiser-bike-7-speed-3.webp"
  ],
  "pedal-brewer-electric-cruiser-bike-reef-blue-468wh": [
    "/images/products/pedal-brewer-electric-cruiser-bike-reef-blue-468wh.webp"
  ],
  "pedal-warrior-2-24-electric-mountain-bike": [
    "/images/products/pedal-warrior-2-24-electric-mountain-bike.webp"
  ],
  "merida-espresso-cc-300-eq-se-electric-hybrid-bike": [
    "/images/products/merida-espresso-cc-300-eq-se-electric-hybrid-bike.webp",
    "/images/products/merida-espresso-cc-300-eq-se-electric-hybrid-bike-2.webp"
  ],
  "merida-eone-sixty-875-electric-enduro-bike-guarded": [
    "/images/products/merida-eone-sixty-875-electric-enduro-bike-guarded.webp"
  ],
  "cube-touring-hybrid-pro-easy-entry-800-electric-hybrid-bike": [
    "/images/products/cube-touring-hybrid-pro-easy-entry-800-electric-hybrid-bike.webp"
  ],
  "cube-kathmandu-hybrid-one-easy-entry-800-electric-hybrid-bike": [
    "/images/products/cube-kathmandu-hybrid-one-easy-entry-800-electric-hybrid-bike.webp"
  ],
  "cube-nuride-hybrid-pro-easy-entry-600-electric-hybrid-bike": [
    "/images/products/cube-nuride-hybrid-pro-easy-entry-600-electric-hybrid-bike.webp"
  ],
  "cube-touring-hybrid-pro-625-easy-entry-electric-hybrid-bike": [
    "/images/products/cube-touring-hybrid-pro-625-easy-entry-electric-hybrid-bike.webp"
  ],
  "merida-efloat-city-400-eq-electric-hybrid-bike": [
    "/images/products/merida-efloat-city-400-eq-electric-hybrid-bike.webp",
    "/images/products/merida-efloat-city-400-eq-electric-hybrid-bike-2.webp"
  ],
  "cube-supreme-hybrid-one-500-electric-hybrid-bike": [
    "/images/products/cube-supreme-hybrid-one-500-electric-hybrid-bike.webp"
  ],
  "cube-touring-hybrid-one-500-electric-hybrid-bike": [
    "/images/products/cube-touring-hybrid-one-500-electric-hybrid-bike.webp"
  ],
  "merida-espresso-city-400-eq-electric-hybrid-bike-silk-warm": [
    "/images/products/merida-espresso-city-400-eq-electric-hybrid-bike-silk-warm.webp",
    "/images/products/merida-espresso-city-400-eq-electric-hybrid-bike-silk-warm-2.webp"
  ],
  "dirodi-rover-pro-250w-electric-fat-bike-caramel-latte": [
    "/images/products/dirodi-rover-pro-250w-electric-fat-bike-caramel-latte.webp"
  ],
  "pedal-falcon-3c-electric-hybrid-bike": [
    "/images/products/pedal-falcon-3c-electric-hybrid-bike.webp"
  ],
  "merida-espresso-city-300-se-eq-electric-hybrid-bike": [
    "/images/products/merida-espresso-city-300-se-eq-electric-hybrid-bike.webp"
  ],
  "cube-reaction-hybrid-pro-800-fe-easy-entry-electric-hardtail-mountain-bike-blackline": [
    "/images/products/cube-reaction-hybrid-pro-800-fe-easy-entry-electric-hardtail-mountain-bike-blackline.webp"
  ],
  "pedal-bandit-mini-14-electric-fat-tyre-bike": [
    "/images/products/pedal-bandit-mini-14-electric-fat-tyre-bike.webp"
  ],
  "merida-espresso-cc-500-eq-electric-hybrid-bike": [
    "/images/products/merida-espresso-cc-500-eq-electric-hybrid-bike.webp",
    "/images/products/merida-espresso-cc-500-eq-electric-hybrid-bike-2.webp"
  ],
  "pedal-falcon-3c-st-electric-hybrid-bike": [
    "/images/products/pedal-falcon-3c-st-electric-hybrid-bike.webp"
  ],
  "cube-stereo-hybrid-one22-pro-800-electric-trail-bike-slab": [
    "/images/products/cube-stereo-hybrid-one22-pro-800-electric-trail-bike-slab.webp"
  ],
  "cube-kathmandu-hybrid-one-ee-800-electric-hybrid-bike": [
    "/images/products/cube-kathmandu-hybrid-one-ee-800-electric-hybrid-bike.webp"
  ],
  "merida-eone-eighty-400-electric-enduro-bike": [
    "/images/products/merida-eone-eighty-400-electric-enduro-bike.webp"
  ],
  "fox-proframe-mips-full-face-helmet": [
    "/images/products/fox-proframe-mips-full-face-helmet.webp"
  ],
  "raven-bmx-helmet": [
    "/images/products/raven-bmx-helmet.webp"
  ],
  "met-crackerjack-kids-helmet-pink-uni-52-57cm": [
    "/images/products/met-crackerjack-kids-helmet-pink-uni-52-57cm.webp",
    "/images/products/met-crackerjack-kids-helmet-pink-uni-52-57cm-2.webp",
    "/images/products/met-crackerjack-kids-helmet-pink-uni-52-57cm-3.webp"
  ],
  "met-rivale-ii-mips-helmet": [
    "/images/products/met-rivale-ii-mips-helmet.webp"
  ],
  "met-hooray-kids-helmet-flowers": [
    "/images/products/met-hooray-kids-helmet-flowers.webp"
  ],
  "met-crackerjack-kids-helmet-cyan-uni-52-57cm": [
    "/images/products/met-crackerjack-kids-helmet-cyan-uni-52-57cm.webp"
  ],
  "met-trenta-mips-helmet": [
    "/images/products/met-trenta-mips-helmet.webp"
  ],
  "raven-corvus-mtb-helmet-with-magnetic-clip": [
    "/images/products/raven-corvus-mtb-helmet-with-magnetic-clip.webp",
    "/images/products/raven-corvus-mtb-helmet-with-magnetic-clip-2.webp"
  ],
  "lazer-finch-kineticore-mtb-helmet-ocean": [
    "/images/products/lazer-finch-kineticore-mtb-helmet-ocean.webp"
  ],
  "bluegrass-superbold-bmx-helmet": [
    "/images/products/bluegrass-superbold-bmx-helmet.webp",
    "/images/products/bluegrass-superbold-bmx-helmet-2.webp"
  ],
  "met-crackerjack-mips-kids-helmet-pink-uni-52-57cm": [
    "/images/products/met-crackerjack-mips-kids-helmet-pink-uni-52-57cm.webp"
  ],
  "met-crackerjack-kids-helmet-petrol-uni-52-57cm": [
    "/images/products/met-crackerjack-kids-helmet-petrol-uni-52-57cm.webp"
  ],
  "cinettica-roar-dinosaur-kids-helmet": [
    "/images/products/cinettica-roar-dinosaur-kids-helmet.webp"
  ],
  "lazer-lupo-kineticore-mtb-helmet-matte-black-uni-55-61cm": [
    "/images/products/lazer-lupo-kineticore-mtb-helmet-matte-black-uni-55-61cm.webp",
    "/images/products/lazer-lupo-kineticore-mtb-helmet-matte-black-uni-55-61cm-2.webp"
  ],
  "met-hooray-mips-kids-helmet-dusted-green-with": [
    "/images/products/met-hooray-mips-kids-helmet-dusted-green-with.webp"
  ],
  "fox-speedframe-charge-youth-mtb-helmet-uni-51-55cm": [
    "/images/products/fox-speedframe-charge-youth-mtb-helmet-uni-51-55cm.webp"
  ],
  "met-hooray-mips-kids-helmet-space-glow-in-the": [
    "/images/products/met-hooray-mips-kids-helmet-space-glow-in-the.webp"
  ],
  "giro-fixture-ii-mips-kids-helmet-matte-black-uni-50-57cm": [
    "/images/products/giro-fixture-ii-mips-kids-helmet-matte-black-uni-50-57cm.webp",
    "/images/products/giro-fixture-ii-mips-kids-helmet-matte-black-uni-50-57cm-2.webp"
  ],
  "lazer-finch-kineticore-mtb-helmet-bright": [
    "/images/products/lazer-finch-kineticore-mtb-helmet-bright.webp"
  ],
  "lazer-finch-kineticore-mtb-helmet": [
    "/images/products/lazer-finch-kineticore-mtb-helmet.webp",
    "/images/products/lazer-finch-kineticore-mtb-helmet-2.webp"
  ],
  "met-hooray-mips-pink-hearts": [
    "/images/products/met-hooray-mips-pink-hearts.webp"
  ],
  "cinettica-roar-cat-kids-helmet": [
    "/images/products/cinettica-roar-cat-kids-helmet.webp"
  ],
  "giro-fixture-ii-youth-mips-mtb-helmet-uni-50-57cm-green-rush": [
    "/images/products/giro-fixture-ii-youth-mips-mtb-helmet-uni-50-57cm-green-rush.webp"
  ],
  "giro-tremor-kids-helmet-uni-47-54cm-blue-trench": [
    "/images/products/giro-tremor-kids-helmet-uni-47-54cm-blue-trench.webp",
    "/images/products/giro-tremor-kids-helmet-uni-47-54cm-blue-trench-2.webp"
  ],
  "hornit-airo-kids-helmet": [
    "/images/products/hornit-airo-kids-helmet.webp"
  ],
  "lazer-finch-kineticore-mtb-helmet-sedona": [
    "/images/products/lazer-finch-kineticore-mtb-helmet-sedona.webp"
  ],
  "met-trenta-3k-carbon-mips-road-helmet-uae-team-emirates-xrg-edition": [
    "/images/products/met-trenta-3k-carbon-mips-road-helmet-uae-team-emirates-xrg-edition.webp"
  ],
  "lazer-compact-helmet-racing-green-uni-54-61cm": [
    "/images/products/lazer-compact-helmet-racing-green-uni-54-61cm.webp"
  ],
  "giro-scamp-ii-mips-kids-helmet-matte-purple-lava": [
    "/images/products/giro-scamp-ii-mips-kids-helmet-matte-purple-lava.webp",
    "/images/products/giro-scamp-ii-mips-kids-helmet-matte-purple-lava-2.webp",
    "/images/products/giro-scamp-ii-mips-kids-helmet-matte-purple-lava-3.webp"
  ],
  "bluegrass-superbold-bmx-helmet-solar": [
    "/images/products/bluegrass-superbold-bmx-helmet-solar.webp"
  ],
  "fox-rampage-comp-mips-fullface-helmet": [
    "/images/products/fox-rampage-comp-mips-fullface-helmet.webp"
  ],
  "lazer-lupo-kineticore-mtb-helmet-dusk-blue-uni-55-61cm": [
    "/images/products/lazer-lupo-kineticore-mtb-helmet-dusk-blue-uni-55-61cm.webp"
  ],
  "lazer-finch-kineticore-mtb-helmet-matte-black-uni-50-56cm": [
    "/images/products/lazer-finch-kineticore-mtb-helmet-matte-black-uni-50-56cm.webp"
  ],
  "lazer-lupo-kineticore-mtb-helmet-matte-flash-orange-uni-55-61cm": [
    "/images/products/lazer-lupo-kineticore-mtb-helmet-matte-flash-orange-uni-55-61cm.webp"
  ],
  "fox-speedframe-pro-mips-mtb-helmet-black-green-50-years-edition": [
    "/images/products/fox-speedframe-pro-mips-mtb-helmet-black-green-50-years-edition.webp"
  ],
  "met-trenta-3k-carbon-mips-road-helmet-glossy": [
    "/images/products/met-trenta-3k-carbon-mips-road-helmet-glossy.webp"
  ],
  "met-trenta-3k-carbon-mips-road-helmet-rainbow-ltd-edition": [
    "/images/products/met-trenta-3k-carbon-mips-road-helmet-rainbow-ltd-edition.webp"
  ],
  "met-trenta-3k-carbon-mips-road-helmet-uae-team-adq-edition": [
    "/images/products/met-trenta-3k-carbon-mips-road-helmet-uae-team-adq-edition.webp"
  ],
  "met-codatronca-triathlon-helmet-glossy": [
    "/images/products/met-codatronca-triathlon-helmet-glossy.webp",
    "/images/products/met-codatronca-triathlon-helmet-glossy-2.webp"
  ],
  "fox-speedframe-pro-mips-mtb-helmet-camo-small": [
    "/images/products/fox-speedframe-pro-mips-mtb-helmet-camo-small.webp"
  ],
  "giro-fixture-ii-youth-mips-mtb-helmet-aqua-green-blue-jewel-fade": [
    "/images/products/giro-fixture-ii-youth-mips-mtb-helmet-aqua-green-blue-jewel-fade.webp",
    "/images/products/giro-fixture-ii-youth-mips-mtb-helmet-aqua-green-blue-jewel-fade-2.webp"
  ],
  "lazer-compact-kineticore-helmet-titanium-uni-54-61cm": [
    "/images/products/lazer-compact-kineticore-helmet-titanium-uni-54-61cm.webp",
    "/images/products/lazer-compact-kineticore-helmet-titanium-uni-54-61cm-2.webp",
    "/images/products/lazer-compact-kineticore-helmet-titanium-uni-54-61cm-3.webp"
  ],
  "met-crackerjack-mips-kids-helmet-cyan-uni-52-57cm": [
    "/images/products/met-crackerjack-mips-kids-helmet-cyan-uni-52-57cm.webp"
  ],
  "met-trenta-pace-ii-mips-road-helmet": [
    "/images/products/met-trenta-pace-ii-mips-road-helmet.webp"
  ],
  "met-trenta-pace-ii-mips-road-helmet-matte-orchid": [
    "/images/products/met-trenta-pace-ii-mips-road-helmet-matte-orchid.webp"
  ],
  "met-trenta-pace-ii-mips-road-helmet-matte-antler": [
    "/images/products/met-trenta-pace-ii-mips-road-helmet-matte-antler.webp"
  ],
  "cinettica-coda-gel-ii-road-gloves": [
    "/images/products/cinettica-coda-gel-ii-road-gloves.webp",
    "/images/products/cinettica-coda-gel-ii-road-gloves-2.webp",
    "/images/products/cinettica-coda-gel-ii-road-gloves-3.webp"
  ],
  "castelli-espresso-road-gloves": [
    "/images/products/castelli-espresso-road-gloves.webp"
  ],
  "cinnetica-thermal-gloves": [
    "/images/products/cinnetica-thermal-gloves.webp"
  ],
  "fist-ch28-mtb-gloves-r-willy-ace": [
    "/images/products/fist-ch28-mtb-gloves-r-willy-ace.webp"
  ],
  "fist-ch24-stocker-mtb-gloves": [
    "/images/products/fist-ch24-stocker-mtb-gloves.webp",
    "/images/products/fist-ch24-stocker-mtb-gloves-2.webp",
    "/images/products/fist-ch24-stocker-mtb-gloves-3.webp"
  ],
  "fist-stocker-youth-gloves": [
    "/images/products/fist-stocker-youth-gloves.webp"
  ],
  "castelli-espresso-womens-road-gloves-pool": [
    "/images/products/castelli-espresso-womens-road-gloves-pool.webp"
  ],
  "fist-stocker-glove": [
    "/images/products/fist-stocker-glove.webp"
  ],
  "bbb-raceshield-full-finger-winter-gloves": [
    "/images/products/bbb-raceshield-full-finger-winter-gloves.webp"
  ],
  "cinettica-ollo-fleece-gloves": [
    "/images/products/cinettica-ollo-fleece-gloves.webp"
  ],
  "fist-ch27-strapped-gloves-fruit-punch": [
    "/images/products/fist-ch27-strapped-gloves-fruit-punch.webp",
    "/images/products/fist-ch27-strapped-gloves-fruit-punch-2.webp"
  ],
  "castelli-espresso-road-gloves-vivid": [
    "/images/products/castelli-espresso-road-gloves-vivid.webp"
  ],
  "bbb-controlzone-touch-screen-winter-gloves": [
    "/images/products/bbb-controlzone-touch-screen-winter-gloves.webp"
  ],
  "fist-ch28-mtb-gloves-100-nuts": [
    "/images/products/fist-ch28-mtb-gloves-100-nuts.webp"
  ],
  "fist-ch28-mtb-gloves-poison": [
    "/images/products/fist-ch28-mtb-gloves-poison.webp"
  ],
  "fist-ch28-mtb-gloves-corey-creed-to-the-moon": [
    "/images/products/fist-ch28-mtb-gloves-corey-creed-to-the-moon.webp"
  ],
  "fox-defend-full-finger-gloves": [
    "/images/products/fox-defend-full-finger-gloves.webp"
  ],
  "fox-ranger-water-full-finger-gloves": [
    "/images/products/fox-ranger-water-full-finger-gloves.webp"
  ],
  "fist-caroline-buchanan-mini-sprinkles-full-finger-youth-mtb-gloves": [
    "/images/products/fist-caroline-buchanan-mini-sprinkles-full-finger-youth-mtb-gloves.webp"
  ],
  "castelli-lightness-3-full-finger-road-gloves": [
    "/images/products/castelli-lightness-3-full-finger-road-gloves.webp"
  ],
  "klip-nova-flex-smart-tags-4-pack": [
    "/images/products/klip-nova-flex-smart-tags-4-pack.webp"
  ],
  "klip-nova-flex-smart-tag": [
    "/images/products/klip-nova-flex-smart-tag.webp"
  ],
  "azur-leo-50-lumen-rear": [
    "/images/products/azur-leo-50-lumen-rear.webp"
  ],
  "pedal-coyote-3-electric-hardtail-mountain-bike": [
    "/images/products/pedal-coyote-3-electric-hardtail-mountain-bike.webp"
  ],
  "pedal-coyote-3-st-tour-electric-hardtail-mountain-bike": [
    "/images/products/pedal-coyote-3-st-tour-electric-hardtail-mountain-bike.webp"
  ],
  "cube-reaction-hybrid-performance-600-electric-hardtail": [
    "/images/products/cube-reaction-hybrid-performance-600-electric-hardtail.webp"
  ],
  "cube-reaction-hybrid-pro-800-electric-hardtail": [
    "/images/products/cube-reaction-hybrid-pro-800-electric-hardtail.webp"
  ],
  "cube-stereo-hybrid-one44-pro-800-electric-trail-bike": [
    "/images/products/cube-stereo-hybrid-one44-pro-800-electric-trail-bike.webp"
  ],
  "cube-stereo-hybrid-one22-pro-600-electric-trail-bike": [
    "/images/products/cube-stereo-hybrid-one22-pro-600-electric-trail-bike.webp"
  ],
  "cube-stereo-hybrid-one44-hpc-race-800-electric-trail-bike": [
    "/images/products/cube-stereo-hybrid-one44-hpc-race-800-electric-trail-bike.webp"
  ],
  "merida-eone-forty-400-electric-trail-bike": [
    "/images/products/merida-eone-forty-400-electric-trail-bike.webp"
  ],
  "cube-stereo-hybrid-one77-hpc-slx-800-electric-enduro-bike": [
    "/images/products/cube-stereo-hybrid-one77-hpc-slx-800-electric-enduro-bike.webp"
  ],
  "cube-stereo-hybrid-one77-hpc-tm-800-electric-enduro-bike": [
    "/images/products/cube-stereo-hybrid-one77-hpc-tm-800-electric-enduro-bike.webp"
  ],
  "merida-eone-sixty-675-electric-enduro-bike": [
    "/images/products/merida-eone-sixty-675-electric-enduro-bike.webp",
    "/images/products/merida-eone-sixty-675-electric-enduro-bike-2.webp"
  ],
  "merida-eone-eighty-500-electric-enduro-bike": [
    "/images/products/merida-eone-eighty-500-electric-enduro-bike.webp"
  ],
  "merida-eone-eighty-700-electric-enduro-bike": [
    "/images/products/merida-eone-eighty-700-electric-enduro-bike.webp"
  ],
  "pedal-eagle-st-electric-hybrid-bike": [
    "/images/products/pedal-eagle-st-electric-hybrid-bike.webp",
    "/images/products/pedal-eagle-st-electric-hybrid-bike-2.webp"
  ],
  "pedal-clipper-2-electric-hybrid-bike": [
    "/images/products/pedal-clipper-2-electric-hybrid-bike.webp"
  ],
  "pedal-comet-3-disc-electric-hybrid-bike": [
    "/images/products/pedal-comet-3-disc-electric-hybrid-bike.webp",
    "/images/products/pedal-comet-3-disc-electric-hybrid-bike-2.webp"
  ],
  "cube-nuride-hybrid-performance-easy-entry-600-electric-hybrid-bike": [
    "/images/products/cube-nuride-hybrid-performance-easy-entry-600-electric-hybrid-bike.webp"
  ],
  "cube-touring-hybrid-pro-800-electric-hybrid-bike": [
    "/images/products/cube-touring-hybrid-pro-800-electric-hybrid-bike.webp"
  ],
  "cube-editor-hybrid-pro-400x-electric-hybrid-bike": [
    "/images/products/cube-editor-hybrid-pro-400x-electric-hybrid-bike.webp"
  ],
  "merida-espresso-cc-400-eq-electric-hybrid-bike": [
    "/images/products/merida-espresso-cc-400-eq-electric-hybrid-bike.webp"
  ],
  "pedal-breeze-e4-electric-cruiser-bike": [
    "/images/products/pedal-breeze-e4-electric-cruiser-bike.webp",
    "/images/products/pedal-breeze-e4-electric-cruiser-bike-2.webp",
    "/images/products/pedal-breeze-e4-electric-cruiser-bike-3.webp"
  ],
  "pedal-uptown-sl-electric-vintage-cruiser-bike": [
    "/images/products/pedal-uptown-sl-electric-vintage-cruiser-bike.webp",
    "/images/products/pedal-uptown-sl-electric-vintage-cruiser-bike-2.webp",
    "/images/products/pedal-uptown-sl-electric-vintage-cruiser-bike-3.webp"
  ],
  "pedal-seahawk-sl-electric-cruiser-bike": [
    "/images/products/pedal-seahawk-sl-electric-cruiser-bike.webp"
  ],
  "dirodi-rover-gen-6-250w-electric-fat-bike": [
    "/images/products/dirodi-rover-gen-6-250w-electric-fat-bike.webp"
  ],
  "dirodi-rover-plus-gen-6-250w-electric-fat-bike": [
    "/images/products/dirodi-rover-plus-gen-6-250w-electric-fat-bike.webp"
  ],
  "dirodi-rover-pro-st-250w-electric-fat-bike": [
    "/images/products/dirodi-rover-pro-st-250w-electric-fat-bike.webp",
    "/images/products/dirodi-rover-pro-st-250w-electric-fat-bike-2.webp"
  ],
  "pedal-nomad-cargo-electric-cargo-bike": [
    "/images/products/pedal-nomad-cargo-electric-cargo-bike.webp"
  ],
  "cube-cargo-sport-dual-hybrid-1000-electric-cargo-bike": [
    "/images/products/cube-cargo-sport-dual-hybrid-1000-electric-cargo-bike.webp"
  ],
  "met-crackerjack-kids-helmet-pink": [
    "/images/products/met-crackerjack-kids-helmet-pink.webp",
    "/images/products/met-crackerjack-kids-helmet-pink-2.webp"
  ],
  "met-hooray-kids-helmet-pink-hearts": [
    "/images/products/met-hooray-kids-helmet-pink-hearts.webp"
  ],
  "met-echo-helmet-black-matte": [
    "/images/products/met-echo-helmet-black-matte.webp",
    "/images/products/met-echo-helmet-black-matte-2.webp",
    "/images/products/met-echo-helmet-black-matte-3.webp"
  ],
  "giro-agilis-mips-road-helmet-matt-white": [
    "/images/products/giro-agilis-mips-road-helmet-matt-white.webp"
  ],
  "cinettica-velocita-road-helmet-black": [
    "/images/products/cinettica-velocita-road-helmet-black.webp"
  ],
  "fox-speedframe-solid-mips-mtb-helmet-matte-black": [
    "/images/products/fox-speedframe-solid-mips-mtb-helmet-matte-black.webp"
  ],
  "giro-jag-non-gel-road-gloves-black": [
    "/images/products/giro-jag-non-gel-road-gloves-black.webp"
  ],
  "giro-bravo-ii-gel-road-gloves-black": [
    "/images/products/giro-bravo-ii-gel-road-gloves-black.webp"
  ],
  "black-mountain-shadow-trail-mtb-gloves-black": [
    "/images/products/black-mountain-shadow-trail-mtb-gloves-black.webp"
  ],
  "black-mountain-shadow-trail-youth-mtb-gloves-black": [
    "/images/products/black-mountain-shadow-trail-youth-mtb-gloves-black.webp"
  ],
  "cinettica-thermal-gloves-black": [
    "/images/products/cinettica-thermal-gloves-black.webp"
  ],
  "segway-ninebot-kickscooter-e2-pro": [
    "/images/products/segway-ninebot-kickscooter-e2-pro.webp"
  ],
  "segway-ninebot-e3-pro": [
    "/images/products/segway-ninebot-e3-pro.webp"
  ],
  "segway-ninebot-c2-pro": [
    "/images/products/segway-ninebot-c2-pro.webp"
  ],
  "segway-ninebot-c2-lite-ekickscooter": [
    "/images/products/segway-ninebot-c2-lite-ekickscooter.webp"
  ],
  "segway-ninebot-kickscooter-f3": [
    "/images/products/segway-ninebot-kickscooter-f3.webp"
  ],
  "segway-ninebot-kickscooter-f3-pro": [
    "/images/products/segway-ninebot-kickscooter-f3-pro.webp"
  ],
  "segway-ninebot-kickscooter-max-g3": [
    "/images/products/segway-ninebot-kickscooter-max-g3.webp"
  ]
};
