// GENERATED by seo-strategy/preview-site/audit.js from the Semrush bank. Do not hand-edit.
// Up to 6 unassigned, same-topic search terms per page (KD <= 30, volume >= 90), shown as "Related searches".
export const RELATED_SEARCHES: Record<string, string[]> = {
  "cheap": [
    "e bikes for sale",
    "discount electric bikes",
    "cheap e cycle",
    "cheap electric bikes australia under $500",
    "cheapest ebikes",
    "discount ebike"
  ],
  "kids-ebikes": [
    "bike for kids",
    "best kids bike",
    "children's bikes",
    "childrens bikes with gears",
    "kids 14 inch bike",
    "childs bike"
  ],
  "sc-electric": [
    "bicycle and scooter",
    "9bot e scooter",
    "9bot electric scooter",
    "scooters handicap"
  ],
  "batteries": [
    "battery operated bicycle for adults",
    "electric cycle battery",
    "electric bike battery 48v",
    "electric bicycle battery replacement",
    "e bike battery charger",
    "e bike battery replacement"
  ],
  "used": [
    "second hand electric cycle",
    "e bike 2nd hand",
    "second hand electric bikes for sale",
    "used electric bikes for sale",
    "second hand electric bicycle",
    "used e-bikes for sale"
  ],
  "brand-segway": [
    "segway electric kickscooter e2 pro",
    "segway-ninebot electric scooter",
    "segway ninebot e2 electric scooter",
    "ninebot e3 pro",
    "segway ninebot e2 e scooter",
    "segway ninebot e3 pro electric scooter"
  ],
  "brand-specialized": [
    "specialized mtb",
    "specialised mtb",
    "specialised mtb bikes",
    "specialized mtb bikes",
    "specialized turbo levo bike",
    "specialised electric bike"
  ],
  "conversion": [
    "e-bike engine",
    "electric bike.conversion",
    "electric bicycle mid drive kit",
    "electric bicycle e bike conversion kits",
    "e bike engine kit",
    "electric bicycle engine kit"
  ],
  "hub": [
    "electric bike repair",
    "small electric bike",
    "australian electric bike",
    "electric bike for adults australia",
    "electric bicycle reviews australia",
    "miniature electric bike"
  ],
  "kids-helmets": [
    "kiddies helmets",
    "childrens crash helmets"
  ],
  "folding": [
    "fold up e bike",
    "foldable electric bike australia",
    "folding electric bikes australia",
    "estate folding e bike",
    "e bike fold",
    "electric bikes fold away"
  ],
  "emtb": [
    "e-mtb sale",
    "e-mtb australia",
    "e mtb bike"
  ],
  "brand-pedal": [
    "kids pedal bike"
  ],
  "gear-accessories": [
    "pedal assist mountain bike",
    "motoneta seat"
  ],
  "emtb-enduro": [
    "mountain biking dh"
  ],
  "trikes": [
    "best electric tricycle for adults australia",
    "electric three wheel bike",
    "electric tricycle for adults australia",
    "3 wheel electric bike australia",
    "3 wheel e bike",
    "e bike tricycle"
  ],
  "emtb-kids": [
    "childs mtb"
  ],
  "commuter": [
    "city e bike",
    "men's electric bicycle",
    "electric city bike",
    "urban electric bicycle",
    "commuter ebike australia",
    "step through e bikes australia"
  ],
  "gear-parts": [
    "ebike wheel"
  ],
  "fat-tyre": [
    "fat tyre electric bike australia",
    "fat tyre ebike australia",
    "electric fat bike australia"
  ],
  "city-sydney": [
    "e bikes for sale sydney"
  ],
  "city-melbourne": [
    "e bikes for sale melbourne",
    "best electric bikes melbourne"
  ],
  "cargo": [
    "best electric cargo bike australia"
  ],
  "city-perth": [
    "electric bike shop perth"
  ],
  "brand-aldi": [
    "aldi estate ebike"
  ],
  "city-brisbane": [
    "electric bikes for sale brisbane",
    "used electric bikes brisbane"
  ],
  "emtb-dual": [
    "dual suspension mountain bike 24 inch"
  ]
};
